quarkus.application.name=flight-service
quarkus.http.port=8081

# Basic Authentication
quarkus.security.users.file.enabled=true
quarkus.security.users.file.users=users.properties
quarkus.security.users.file.roles=roles.properties
quarkus.security.users.file.plain-text=true
quarkus.http.auth.basic=true

# PostgreSQL datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=flightuser
quarkus.datasource.password=flightpass
# LOCAL DEV
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/flightsdb

# CONTAINER / PROD
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/flightsdb

# Hibernate
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

# SQL logs
quarkus.hibernate-orm.log.sql=true