quarkus.application.name=flight-service
quarkus.http.port=8081

# PostgreSQL datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=flightuser
quarkus.datasource.password=flightpass
quarkus.datasource.jdbc.url=jdbc:postgresql://172.31.28.245:5432/flightdb

# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create

# SQL logs
quarkus.hibernate-orm.log.sql=true