quarkus.application.name=reservation-service
quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8080}

# Basic Authentication
quarkus.security.users.file.enabled=true
quarkus.security.users.file.users=users.properties
quarkus.security.users.file.roles=roles.properties
quarkus.security.users.file.plain-text=true
quarkus.http.auth.basic=true

# PostgreSQL datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=reservationuser
quarkus.datasource.password=reservationpass
# LOCAL DEV
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://172.31.28.245:5432/reservationsdb

# CONTAINER / PROD
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql:///reservationsdb?cloudSqlInstance=portfolio-apigee-demo:europe-west9:travel-postgres&socketFactory=com.google.cloud.sql.postgres.SocketFactory

# Hibernate
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

# SQL logs
quarkus.hibernate-orm.log.sql=true